create table "public"."Blogs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Blogs" enable row level security;

CREATE UNIQUE INDEX "Blogs_pkey" ON public."Blogs" USING btree (id);

alter table "public"."Blogs" add constraint "Blogs_pkey" PRIMARY KEY using index "Blogs_pkey";

grant delete on table "public"."Blogs" to "anon";

grant insert on table "public"."Blogs" to "anon";

grant references on table "public"."Blogs" to "anon";

grant select on table "public"."Blogs" to "anon";

grant trigger on table "public"."Blogs" to "anon";

grant truncate on table "public"."Blogs" to "anon";

grant update on table "public"."Blogs" to "anon";

grant delete on table "public"."Blogs" to "authenticated";

grant insert on table "public"."Blogs" to "authenticated";

grant references on table "public"."Blogs" to "authenticated";

grant select on table "public"."Blogs" to "authenticated";

grant trigger on table "public"."Blogs" to "authenticated";

grant truncate on table "public"."Blogs" to "authenticated";

grant update on table "public"."Blogs" to "authenticated";

grant delete on table "public"."Blogs" to "service_role";

grant insert on table "public"."Blogs" to "service_role";

grant references on table "public"."Blogs" to "service_role";

grant select on table "public"."Blogs" to "service_role";

grant trigger on table "public"."Blogs" to "service_role";

grant truncate on table "public"."Blogs" to "service_role";

grant update on table "public"."Blogs" to "service_role";


